Return the key's bits upon import
AndrzejKurek/mbed-os-atecc608a pull request #1
Opened 2019-09-04 14:31 UTC by k-stachowiak

This PR enables handling the out parameter to the `atecc608a_import_public_key()` function stating, how many bits does the imported key have.

2019-09-04 14:41 UTC, AndrzejKurek commented on atecc608a_se.c
> +        /* The 64-byte key is written as 72 bytes, but we return 64 as the
I would just mention about the secure element here: It is stored in SE as 72 bytes.

2019-09-04 14:43 UTC, AndrzejKurek requested changes
Please reword the comment a bit.

2019-09-05 08:26 UTC, k-stachowiak commented
I have rebased the PR upon conflicts. The single commit now contains a fixed commit.

2019-09-05 08:55 UTC, AndrzejKurek approved these changes

2019-09-05 08:55 UTC, merged